### ISSUE TITLE
Event object data field not populated on initialization

### ISSUE THREAD

**Issue by criskim** [fhwang/event_sourced_record#19]
It seems like unless the attributes for an event object are defined specifically using attr_accessible they will either not be passed onto the data field or raise an exception. It did raise an exception on a clean new Rails project but in one of our applications it just initialized the event object with an empty data field.

Example on a clean Rails 3.2.17 project without attr_accessible set:

```
class SubscriptionEvent < ActiveRecord::Base
  include EventSourcedRecord::Event

  serialize :data

  belongs_to :subscription,
    foreign_key: 'subscription_uuid', primary_key: 'uuid'

  event_type :creation do
    attributes :user_id

    validates :user_id, presence: true
  end

end
```

```
1.9.3-p551 :002 > SubscriptionEvent.creation.new(user_id: 123)
ActiveModel::MassAssignmentSecurity::Error: Can't mass-assign protected attributes: user_id
    from /Users/cdk/.rvm/gems/ruby-1.9.3-p551@estest/gems/activemodel-3.2.17/lib/active_model/mass_assignment_security/sanitizer.rb:48:in `process_removed_attributes'
    from /Users/cdk/.rvm/gems/ruby-1.9.3-p551@estest/gems/activemodel-3.2.17/lib/active_model/mass_assignment_security/sanitizer.rb:20:in `debug_protected_attribute_removal'
    from /Users/cdk/.rvm/gems/ruby-1.9.3-p551@estest/gems/activemodel-3.2.17/lib/active_model/mass_assignment_security/sanitizer.rb:12:in `sanitize'
    from /Users/cdk/.rvm/gems/ruby-1.9.3-p551@estest/gems/activemodel-3.2.17/lib/active_model/mass_assignment_security.rb:230:in `sanitize_for_mass_assignment'
    from /Users/cdk/.rvm/gems/ruby-1.9.3-p551@estest/gems/activerecord-3.2.17/lib/active_record/attribute_assignment.rb:75:in `assign_attributes'
    from /Users/cdk/.rvm/gems/ruby-1.9.3-p551@estest/gems/activerecord-3.2.17/lib/active_record/base.rb:498:in `initialize'
    from /Users/cdk/.rvm/gems/ruby-1.9.3-p551@estest/gems/activerecord-3.2.17/lib/active_record/relation.rb:76:in `new'
    from /Users/cdk/.rvm/gems/ruby-1.9.3-p551@estest/gems/activerecord-3.2.17/lib/active_record/relation.rb:76:in `block in new'
    from /Users/cdk/.rvm/gems/ruby-1.9.3-p551@estest/gems/activerecord-3.2.17/lib/active_record/relation.rb:241:in `block in scoping'
    from /Users/cdk/.rvm/gems/ruby-1.9.3-p551@estest/gems/activerecord-3.2.17/lib/active_record/scoping.rb:98:in `with_scope'
    from /Users/cdk/.rvm/gems/ruby-1.9.3-p551@estest/gems/activerecord-3.2.17/lib/active_record/relation.rb:241:in `scoping'
    from /Users/cdk/.rvm/gems/ruby-1.9.3-p551@estest/gems/activerecord-3.2.17/lib/active_record/relation.rb:76:in `new'
    from (irb):2
    from /Users/cdk/.rvm/gems/ruby-1.9.3-p551@estest/gems/railties-3.2.17/lib/rails/commands/console.rb:47:in `start'
    from /Users/cdk/.rvm/gems/ruby-1.9.3-p551@estest/gems/railties-3.2.17/lib/rails/commands/console.rb:8:in `start'
    from /Users/cdk/.rvm/gems/ruby-1.9.3-p551@estest/gems/railties-3.2.17/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'1.9.3-p551 :003 >
```

Example on a clean Rails 3.2.17 project with attr_accessible set:

```
class SubscriptionEvent < ActiveRecord::Base
  include EventSourcedRecord::Event

  attr_accessible :user_id

  serialize :data

  belongs_to :subscription,
    foreign_key: 'subscription_uuid', primary_key: 'uuid'

  event_type :creation do
    attributes :user_id

    validates :user_id, presence: true
  end

end
```

```
1.9.3-p551 :004 > SubscriptionEvent.creation.new(user_id: 123)
 => #<SubscriptionEvent id: nil, subscription_uuid: "b6ecb434-dcfd-4fad-8c16-6906a4c018ba", event_type: :creation, data: {"user_id"=>123}, created_at: nil, occurred_at: nil>
```

**Comment by fhwang** [comment]
I think this is more or less how this should act: In general these extra event-specific attributes should act like normal model attributes whenever possible. This is just something I hadn't noticed before (probably because most of this library's users are using it with Rails 4, which doesn't do mass assignment protection in this way).

My fix to this is simply to make a note of this in the documentation. Thanks for pointing this out, though.
